version: "3" # docker-compose version
services: # services which our app going to use. (list of containers we want to create)
  mongo: # container name
    image: mongo # On which image container will build
    ports:
      - "27017:27017"
